
title: My Resume
url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: 唐鹏
tagline: Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: tang.peng@hotmail.com
phone: 18676361392
website: tangpengcsu.github.io/blog #do not add http://
linkedin: 鹏-唐-585098113
github: tangpengcsu
#twitter: '@webjeda'

#Update all the sections by editing the files inside _includes folder.
